/*
  Auto-generated by Spline
*/
"use client";
import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline('https://prod.spline.design/yo7CTbLuWjxbg11U/scene.splinecode')
    return (
        <>
            <color attach="background" args={['#ffffff']} />
            <group {...props} dispose={null}>
                <mesh
                    name="Text"
                    geometry={nodes.Text.geometry}
                    material={materials['Text Material']}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    rotation={[0, -Math.PI / 2, 0]}
                />
                <PerspectiveCamera
                    name="1"
                    makeDefault={true}
                    far={100000}
                    near={70}
                    fov={45}
                    position={[-286.77, 62.52, 72.79]}
                    rotation={[-0.59, -1.3, -0.57]}
                />
                <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
            </group>
        </>
    )
}
