/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline('https://prod.spline.design/yo7CTbLuWjxbg11U/scene.splinecode')
    return (
        <>
            <color attach="background" args={['#ffffff']} />
            <group {...props} dispose={null}>
                <group name="Text" position={[5,-10,-30]}>
                    <mesh
                        name="Text 2"
                        geometry={nodes['Text 2'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-47.72, 2.14, 0]}
                    />
                    <mesh
                        name="Text 21"
                        geometry={nodes['Text 21'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-38.14, 2.14, 0]}
                    />
                    <mesh
                        name="Text 22"
                        geometry={nodes['Text 22'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-28.52, 2.14, 0]}
                    />
                    <mesh
                        name="Text 23"
                        geometry={nodes['Text 23'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-19.92, 2.14, 0]}
                    />
                    <mesh
                        name="Text 24"
                        geometry={nodes['Text 24'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-8.99, 2.14, 0]}
                    />
                    <mesh
                        name="Text 25"
                        geometry={nodes['Text 25'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[-1.63, 2.14, 0]}
                    />
                    <mesh
                        name="Text 26"
                        geometry={nodes['Text 26'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[7.6, 2.14, 0]}
                    />
                    <mesh
                        name="Text 27"
                        geometry={nodes['Text 27'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[14.12, 2.14, 0]}
                    />
                    <mesh
                        name="Text 28"
                        geometry={nodes['Text 28'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[21.87, 2.14, 0]}
                    />
                    <mesh
                        name="Text 29"
                        geometry={nodes['Text 29'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[30.94, 2.14, 0]}
                    />
                    <mesh
                        name="Text 210"
                        geometry={nodes['Text 210'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[39.18, 2.14, 0]}
                    />
                    <mesh
                        name="Text 211"
                        geometry={nodes['Text 211'].geometry}
                        material={materials['Text Material']}
                        castShadow
                        receiveShadow
                        position={[46.24, 2.14, 0]}
                    />
                </group>
                <PerspectiveCamera
                    name="1"
                    makeDefault={true}
                    far={1000}
                    near={10}
                    fov={45}
                    position={[-20, 10, 60]}
                    rotation={[0, 0, 0]}
                    scale={1}
                />
                <hemisphereLight name="Default Ambient Light" intensity={4.79} color="#eaeaea" />
            </group>
        </>
    )
}
